# templates/__init__.py
from templates.mensajes import (
    MENU_PRINCIPAL,
    SUBLIMACION_INFO,
    DTF_INFO,
    CONSULTA_PEDIDO,
    HABLAR_HUMANO,
    PEDIDO_CONFIRMADO,
    ESTADO_PEDIDO,
    PEDIDO_NO_ENCONTRADO,
    MENSAJE_NO_ENTENDIDO,
    DESPEDIDA
)

__all__ = [
    'MENU_PRINCIPAL',
    'SUBLIMACION_INFO',
    'DTF_INFO',
    'CONSULTA_PEDIDO',
    'HABLAR_HUMANO',
    'PEDIDO_CONFIRMADO',
    'ESTADO_PEDIDO',
    'PEDIDO_NO_ENCONTRADO',
    'MENSAJE_NO_ENTENDIDO',
    'DESPEDIDA'
]
